# Generated by Django 5.0.3 on 2024-03-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='principal_login',
        ),
    ]
