# Generated by Django 5.0.3 on 2024-03-12 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_rename_login_principal_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='principal_login',
            name='role',
        ),
    ]
